on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '19'

      - name: Populate AWS Amplify Configuration file from Secrets
        run: |
          mkdir publishing-example-app/src/main/res/raw
          echo "$AMPLIFY_CONFIGURATION" > publishing-example-app/src/main/res/raw/amplifyconfiguration.json
        env:
          AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}

      - run: ./gradlew assemble --stacktrace
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ORG_GRADLE_PROJECT_ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          ORG_GRADLE_PROJECT_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - uses: actions/upload-artifact@v3
        with:
          name: publishing-sdk-debug
          path: publishing-sdk/build/outputs/aar/publishing-sdk-debug.aar
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: publishing-sdk-release
          path: publishing-sdk/build/outputs/aar/publishing-sdk-release.aar
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: subscribing-sdk-debug
          path: subscribing-sdk/build/outputs/aar/subscribing-sdk-debug.aar
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: subscribing-sdk-release
          path: subscribing-sdk/build/outputs/aar/subscribing-sdk-release.aar
          if-no-files-found: error

      # The Kotlin example apps were once being uploaded as workflow artifacts.
      # We're not doing that anymore so we're going to just validate that something got assembled for them.
      - name: Validate that Kotlin Example App APKs were Generated
        run: |
          ls -lR subscribing-example-app/build/outputs/apk/debug/
          ls -lR subscribing-example-app/build/outputs/apk/release/
          ls -lR publishing-example-app/build/outputs/apk/debug/
          ls -lR publishing-example-app/build/outputs/apk/release/

      # The Java app variants are not functional as they are just used to validate build and run tests.
      # So just validate that something got assembled for them.
      - name: Validate that Java APKs were Generated
        run: |
          ls -lR publishing-java-testing/build/outputs/apk/
          ls -lR subscribing-java-testing/build/outputs/apk/
