on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assemble
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ORG_GRADLE_PROJECT_ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          ORG_GRADLE_PROJECT_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      # TODO upload AAR and APK artifacts somewhere for ease of access
      - run: ls -l publishing-sdk/build/outputs/aar/
      - run: ls -l subscribing-sdk/build/outputs/aar/
      - run: ls -lR publishing-example-app/build/outputs/apk/
      - run: ls -lR publishing-example-java-app/build/outputs/apk/
      - run: ls -lR subscribing-example-app/build/outputs/apk/
      - run: ls -lR subscribing-example-java-app/build/outputs/apk/
