on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew check --profile
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ORG_GRADLE_PROJECT_ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          ORG_GRADLE_PROJECT_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-profile-report
          path: build/reports/profile/
      - run: ./gradlew testDebugUnitTestCoverage
      - uses: actions/upload-artifact@v2
        with:
          name: subscribing-sdk-test-coverage
          path: subscribing-sdk/build/reports/jacoco/
      - uses: actions/upload-artifact@v2
        with:
          name: publishing-sdk-test-coverage
          path: publishing-sdk/build/reports/jacoco/
      - uses: actions/upload-artifact@v2
        with:
          name: core-sdk-test-coverage
          path: core-sdk/build/reports/jacoco/
