on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Compatibility documentation:
        # https://docs.gradle.org/current/userguide/compatibility.html#java
        # https://developer.android.com/studio/releases/gradle-plugin#7-4-0
        java-version: [
          11, # Minimum for the Gradle Android plugin version 7.4.0
          16, # Maximum for Gradle version 7.0
          19, # Maximum for Gradle version 7.6
        ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - run: ./gradlew check testDebugUnitTestCoverage testReleaseUnitTestCoverage --stacktrace --profile -PruntimeSecrets=USE_DUMMY_EMPTY_STRING_VALUES
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      # Reveal potential locations of test build reports
      # (temporary: we'll remove this once we've confirmed where they all end up)
      - run: find . -name "index.html"
        if: always()

      - uses: actions/upload-artifact@v3
        name: Build Reports for common
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-common-build-reports
          path: common/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for integration-testing-app
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-integration-testing-app-build-reports
          path: integration-testing-app/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for publishing-example-app
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-publishing-example-app-build-reports
          path: publishing-example-app/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for publishing-java-testing
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-publishing-java-testing-build-reports
          path: publishing-java-testing/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for publishing-sdk
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-publishing-sdk-build-reports
          path: publishing-sdk/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for subscribing-java-testing
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-subscribing-java-testing-build-reports
          path: subscribing-java-testing/build/reports

      - uses: actions/upload-artifact@v3
        name: Build Reports for subscribing-sdk
        if: always()
        with:
          name: java-version-${{ matrix.java-version }}-subscribing-sdk-build-reports
          path: subscribing-sdk/build/reports
