on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v2

      # Gradle 7 requires Java 11 to run
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build Documentation
        run: |
          ./gradlew dokkaHtmlMultiModule
          ls -al build/dokka/htmlMultiModule
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Configure AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK}}:role/ably-sdk-builds-ably-asset-tracking-android
        role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - uses: ably/sdk-upload-action@v1
        with:
          sourcePath: build/dokka/htmlMultiModule
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dokka
