on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v2

      # Gradle 7 requires Java 11 to run
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build Documentation
        run: |
          ./gradlew dokkaHtmlMultiModule
          ls -al build/dokka/htmlMultiModule
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - uses: ably/sdk-upload-action@v1
        with:
          s3AccessKeyId: ${{ secrets.SDK_S3_ACCESS_KEY_ID }}
          s3AccessKey: ${{ secrets.SDK_S3_ACCESS_KEY }}
          sourcePath: build/dokka/htmlMultiModule
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dokka
