on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 21, 24, 27, 29 ]
        include:
          - api: 21
            excludeModules: true
    steps:
      - uses: actions/checkout@v2

      # Gradle 7 requires Java 11 to run
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          #Github's default -no-snapshot option causes check workflow failing.It is likely because it has to cold boot
          #emulator which might be taking long and causing a timeout issue or a freeze.
          #Adding -no-snapshot-save will enable quick
          #boot. See https://developer.android.com/studio/run/emulator-commandline#common for more
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          # ${{ condition && 'ifTrue' || 'ifFalse' }} is a workaround for a ternary operator https://github.com/actions/runner/issues/409#issuecomment-752775072
          script: ${{ matrix.excludeModules && './gradlew connectedCheck -x :publishing-java-testing:connectedCheck -x :subscribing-java-testing:connectedCheck -x :publishing-example-app:connectedCheck -x :subscribing-example-app:connectedCheck' || './gradlew connectedCheck' }}
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ORG_GRADLE_PROJECT_ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          ORG_GRADLE_PROJECT_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
