# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

name: Publish to GitHub Packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, without v prefix, appended to v to locate tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:

    - uses: actions/checkout@v3
      with:
        ref: v${{ github.event.inputs.version }}

    # Gradle 7 requires Java 11 to run
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '19'

    - name: Publish to Repositories
      env:
        ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.MAVEN_SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
        ORG_GRADLE_PROJECT_SIGNING_KEY_BASE64: ${{ secrets.MAVEN_SIGNING_KEY_RING_FILE_BASE64 }}
      run: |
        echo "Publishing version ${{ github.event.inputs.version }} to GitHub Packages..."
        ./gradlew publish --stacktrace -PpublishTarget=GitHubPackages -PruntimeSecrets=USE_DUMMY_EMPTY_STRING_VALUES
