# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, without v prefix, appended to v to locate tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
        #  with:
        #  distribution: adopt
      #  java-version: 11
      with:
        ref: v${{ github.event.inputs.version }}

      # Gradle 7 requires Java 11 to run
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

  - name: Release build
      # assembleRelease for all modules, excluding non-library modules
      run: ./gradlew assembleRelease -x :android-test-common:assembleRelease -x :test-common:assembleRelease -x
      :integration-testing-app:assembleRelease -x :publishing-example-app:assembleRelease -x
      :publishing-java-testing:assembleRelease -x :subscribing-example-app:assembleRelease -x :subscribing-java-testing:assembleRelease
      - name: Source jar and dokka
        run: ./gradlew androidSourcesJar javadocJar
      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository
        env:
          ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ORG_GRADLE_PROJECT_ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          ORG_GRADLE_PROJECT_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          # Following two may not be needed anymore
          ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SNAPSHOT: true
    run: |
      echo "Publishing version ${{ github.event.inputs.version }}..."
      ./gradlew publish

