# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, without v prefix, appended to v to locate tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: v${{ github.event.inputs.version }}

    - name: Publish to Repositories
      env:
        ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Publishing version ${{ github.event.inputs.version }}..."
        ./gradlew publish
